export const NEWS_CATEGORY_FETCH_REQUEST = 'NEWS_CATEGORY_FETCH_REQUEST'
export const NEWS_CATEGORY_FETCH_RECEIVE = 'NEWS_CATEGORY_FETCH_RECEIVE'
export const NEWS_CATEGORY_FETCH_REJECTED = 'NEWS_CATEGORY_FETCH_REJECTED'
export const NEWS_CATEGORY_FETCH_CANCELLED = 'NEWS_CATEGORY_FETCH_CANCELLED'
