export const APP_SET_ERROR = 'APP_SET_ERROR'

export const NEWS_ARTICLE_REQUEST = 'NEWS_ARTICLE_REQUEST'
export const NEWS_ARTICLE_RECEIVE = 'NEWS_ARTICLE_RECEIVE'
export const NEWS_SOURCE_OPTIONS_REQUEST = 'NEWS_SOURCE_OPTIONS_REQUEST'
export const NEWS_SOURCE_OPTIONS_RECEIVE = 'NEWS_SOURCE_OPTIONS_RECEIVE'
export const NEWS_SOURCE_OPTIONS_SELECT = 'NEWS_SOURCE_OPTIONS_SELECT'
