export const NEWS_SOURCE_FETCH_REQUEST = 'NEWS_SOURCE_FETCH_REQUEST'
export const NEWS_SOURCE_FETCH_RECEIVE = 'NEWS_SOURCE_FETCH_RECEIVE'
export const NEWS_SOURCE_FETCH_REJECTED = 'NEWS_SOURCE_FETCH_REJECTED'
export const NEWS_SOURCE_FETCH_CANCELLED = 'NEWS_SOURCE_FETCH_CANCELLED'
