export const NEWS_ARTICLE_FETCH_REQUEST = 'NEWS_ARTICLE_FETCH_REQUEST'
export const NEWS_ARTICLE_FETCH_RECEIVE = 'NEWS_ARTICLE_FETCH_RECEIVE'
export const NEWS_ARTICLE_FETCH_REJECTED = 'NEWS_ARTICLE_FETCH_REJECTED'
export const NEWS_ARTICLE_FETCH_CANCELLED = 'NEWS_ARTICLE_FETCH_CANCELLED'
